export type { IProvider, ConnectionOptions, ConnectionResult, QRCodeResult, SendMessageOptions, SendMessageResult, MessageContent, AuthState, PresenceType, MediaType } from './i-provider';
export type { IConnection, ConnectionInfo } from './i-connection';
export type { ISessionStore, SessionData } from './i-session-store';
export type { IMessageSender, SentMessage } from './i-message-sender';
export type { IMessageReceiver } from './i-message-receiver';
export type { IQrProvider, QrCodeData } from './i-qr-provider';
export type { IWebhookPublisher, IncomingMessage, MessageStatusUpdate, IncomingMessageHandler } from './i-webhook-publisher';
export type { IProviderFactory } from './i-provider-factory';
export type { ProviderCapabilities, ProviderFeatures, ProviderLimits, RateLimit } from './provider-capabilities';
export type { IProviderRegistry } from './i-provider-registry';
export type { ProviderHealth } from './provider-health';
export type { ProviderMetrics, IProviderMetricsCollector } from './provider-metrics';
