export const EventNames = {
  // Instance Events
  INSTANCE_CREATED: 'INSTANCE_CREATED',
  INSTANCE_CONNECTING: 'INSTANCE_CONNECTING',
  INSTANCE_CONNECTED: 'INSTANCE_CONNECTED',
  INSTANCE_DISCONNECTED: 'INSTANCE_DISCONNECTED',
  INSTANCE_ERROR: 'INSTANCE_ERROR',
  INSTANCE_DISABLED: 'INSTANCE_DISABLED',
  INSTANCE_DELETED: 'INSTANCE_DELETED',

  // Session Events
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_RESTORED: 'SESSION_RESTORED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_DELETED: 'SESSION_DELETED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // QR Events
  QR_GENERATED: 'QR_GENERATED',
  QR_SCANNED: 'QR_SCANNED',
  QR_EXPIRED: 'QR_EXPIRED',

  // Message Events
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_DELIVERED: 'MESSAGE_DELIVERED',
  MESSAGE_READ: 'MESSAGE_READ',
  MESSAGE_FAILED: 'MESSAGE_FAILED',
  MESSAGE_RETRYING: 'MESSAGE_RETRYING',
  MESSAGE_SEND_REQUEST: 'MESSAGE_SEND_REQUEST',

  // Conversation Events
  CONVERSATION_CREATED: 'CONVERSATION_CREATED',
  CONVERSATION_UPDATED: 'CONVERSATION_UPDATED',
  CONVERSATION_CLOSED: 'CONVERSATION_CLOSED',
  CONVERSATION_REOPENED: 'CONVERSATION_REOPENED',

  // Customer Events
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_FIRST_ORDER: 'CUSTOMER_FIRST_ORDER',

  // Order Events
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_PAYMENT_UPDATED: 'ORDER_PAYMENT_UPDATED',

  // Product Events
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_LOW_STOCK: 'PRODUCT_LOW_STOCK',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',

  // Store Events
  STORE_CREATED: 'STORE_CREATED',
  STORE_UPDATED: 'STORE_UPDATED',
  STORE_DEACTIVATED: 'STORE_DEACTIVATED',

  // Automation Events
  WORKFLOW_CREATED: 'WORKFLOW_CREATED',
  WORKFLOW_EXECUTED: 'WORKFLOW_EXECUTED',
  WORKFLOW_FAILED: 'WORKFLOW_FAILED',
  TRIGGER_FIRED: 'TRIGGER_FIRED',

  // AI Events
  AI_REQUEST_STARTED: 'AI_REQUEST_STARTED',
  AI_REQUEST_COMPLETED: 'AI_REQUEST_COMPLETED',
  AI_REQUEST_FAILED: 'AI_REQUEST_FAILED',
  AI_RESPONSE_GENERATED: 'AI_RESPONSE_GENERATED',

  // Audit Events
  AUDIT_LOG_CREATED: 'AUDIT_LOG_CREATED',

  // System Events
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  SYSTEM_HEALTH_CHECK: 'SYSTEM_HEALTH_CHECK',

  // Notification Events
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
} as const;

export type EventName = (typeof EventNames)[keyof typeof EventNames];
